### PR TITLE
These should be all the missing authors

### PR DESCRIPTION
**Pull request by jeremyzilar**
Here is the current list of authors that we have on the site: http://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.s3-website-us-gov-west-1.amazonaws.com/site/gsa/digital.gov/authors/

Let me know if you see anything missing or wrong with these authors. Any additional data can be added in now or at a later point.

### CODE REVIEW

**Comment by AndreaSigz** [comment]
@jz I counted 8 missing from the new list vs. the old list.

- [ ] admin

- [ ] alex-yale-loehr

- [ ] codegov

- [ ] donna-dodson

- [ ] jaime-mears

- [ ] jeremyzilar

- [ ] raquel-romano

- [ ] samantha-hinz

**Comment by jeremyzilar** [comment]
Thank you @AndreaSigz — I should have looked at the published result of the branch before submitting a pull-request for review. 

Here is the branch preview: https://federalist-proxy.app.cloud.gov/preview/gsa/digital.gov/missing-authors/authors/

**Comment by jeremyzilar** [comment]
Ok, here is the current list of authors: https://federalist-proxy.app.cloud.gov/preview/gsa/digital.gov/missing-authors/authors/
I am pretty sure I got them all

**Comment by jeremyzilar** [comment]
If this looks good to you @AndreaSigz, feel free to merge the pull request

**Comment by thisisdano** [comment]
@jeremyzilar @AndreaSigz Looks like these new authors don't have their biographical info and social accts. Can we add that?

For instance, https://www.digitalgov.gov/author/ktrebon/

**Comment by AndreaSigz** [comment]
I don't see admin in the new list @jz. On purpose?

**Pull request merged**
